### ISSUE TITLE
Is there the picture of "ESP32 DEVKIT DOIT" board?

### ISSUE THREAD

**Issue by br76530067** [DiegoPaezA/FreeRTOS_Examples#1]
Hi, Could you give us a picture or detailed SoC type inside this "ESP32 DEVKIT DOIT" board? I want to try so need to buy the same one as you. Thanks!

**Comment by DiegoPaezA** [comment]
Hi, 

The [ESP32 DEVKIT DOIT board](https://makeradvisor.com/tools/esp32-dev-board-wi-fi-bluetooth/) or [ESP32 DEVKit V1](https://www.saravati.com.br/placa-esp32-wifi-/-bluetooth-devkit-v1-30-pinos) has the ESP-WROOM-32 chip.
