### ISSUE TITLE
The link to "Setting up Your Environment " is dead

### ISSUE THREAD

**Issue by equaser** [DiegoPaezA/FreeRTOS_Examples#2]
Hello,
the link to [Setting up Your Environment](https://www.learnesp32.com/2_introduction) is dead. please fix. 
Thank

**Comment by DiegoPaezA** [comment]
Hi, i have to update that part of the repository. I used as reference the course [https://learnesp32.com/](https://learnesp32.com/) and forgot update the wifi readme files. 

[https://learnesp32.com/videos/course-introduction/course-introduction](https://learnesp32.com/videos/course-introduction/course-introduction)
